### ISSUE TITLE
Grafana 13 support: replace react-sortable-hoc (React 19 removed findDOMNode)

### ISSUE THREAD

**Issue by loks0n** [appwrite/grafana-oncall#14]
Blocked out of #9 / #11, which added Grafana 12 and 13 to the e2e matrix. **Grafana 12.4.8 is nearly fine** (3 test-selector failures, fixed in #11), but **Grafana 13.1.3 breaks the plugin for real.**

## Root cause

Grafana 13 ships **React 19**, which removed `ReactDOM.findDOMNode`. The plugin depends on `react-sortable-hoc@1.11.0` (unmaintained, last release 2020), which calls it:

```
TypeError: (0 , xy.findDOMNode) is not a function
  at react-sortable-hoc.esm.js:1427
  at getContainer (react-sortable-hoc.esm.js:1174)
  at commitLayoutEffectOnFiber (react-dom-19/cjs/react-dom-client.production.js:9904)
```

Any page rendering a sortable list throws on mount, which is why ~10 unrelated e2e tests fail on 13 (escalation chains, schedules, users/me, integrations, maintenance mode, plugin extension registration).

## Work

Replace `react-sortable-hoc` with `@dnd-kit`, which is **already a dependency** and already used elsewhere in the plugin, in these 5 files:

- `src/components/SortableList/SortableList.tsx`
- `src/components/UserGroups/UserGroups.tsx`
- `src/components/Policy/DragHandle.tsx`
- `src/components/Policy/EscalationPolicy.tsx`
- `src/components/Policy/NotificationPolicy.tsx`

Then add `13.1.3` back to the e2e matrix in `.github/workflows/linting-and-tests.yml` and expect a second round of selector fixes — Grafana 13 also rewrote `TimeOfDayPicker` as a `Combobox` (11 used `rc-time-picker`, 12 uses `@rc-component/picker`, 13 uses `Combobox`), so the time-picker helpers in `addOverride`/`addRotation`/`escalationPolicy` tests will need updating again.

Probably also worth bumping `@grafana/*` packages from `^11.1.3` toward the target version while doing this.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
